baseURL: http://the-tonal-ligand.com/
languageCode: en-us
title: "the tonal ligand"
theme: yourfolio
disableKinds: [RSS, taxonomy, taxonomyTerm]
relativeURLs: true

menu:
 main:
  - name: About
    weight: 1
    url: /about
  - name: Contact
    weight: 2
    url: /contact
  - name: Research
    weight: 3
    url: /research

# Custom params
params:
  env: development
  logoImage: img/logo.png
  logofile: img/logo.png
  logoImageAlt: the tonal ligand logo
