baseurl = "https://the-tonal-ligand.com/"
disqusShortname = "the-tonal-ligand"
googleAnalytics = ""
languageCode = "en-us"
theme = "hugo-creative-portfolio-theme"
title = "the tonal ligand"
[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"
  description = "The Tonal Ligand"
  copyright = "&copy;2018 by the artists"
  sidebarAbout = [
    "the tonal ligand is musical research into cellular communication. We are musicians exploring new frontiers in biology."
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "team@the-tonal-ligand.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "home"
  url = "home/"
  home = true

  [[params.navlinks]]
  name = "presentation"
  url = "presentation/"
  home = false

  [[params.navlinks]]
  name = "exhibit: affinities"
  url = "affinities/"

  [[params.navlinks]]
  name = "research"
  url = "research/"

  [[params.navlinks]]
  name = "team"
  url = "team/"
  home = false

   [[params.navlinks]]
  name = "contact"
  url = "contact/"

  [params.social]
    instagram     = "https://www.instagram.com/explore/tags/biodesignchallenge/"
    email         = "team@the-tonal-ligand.com"
  # facebook      = "full page or profile url in facebook"
  # googleplus    = "full profile url in googleplus"
  # twitter       = "full profile url in twitter"
  # linkedin      = "full profile url in linkedin"
  # stackoverflow = "full profile url in stackoverflow"
  # github        = "full profile url in github"
  # youtube       = "full profile url in youtube"

